CREATE TABLE [dbo].[Customer]
(
	[Id] INT IDENTITY(1,1) NOT NULL , 
    [Firstname] VARCHAR(100) NOT NULL, 
    [Lastname] VARCHAR(100) NULL, 
    [Email] VARCHAR(50) NOT NULL,
    [Password] VARCHAR(200) NOT NULL,
    [Contact] NVARCHAR(10) NULL, 
    [Address] NVARCHAR(MAX) NULL,
    [RoleId] SMALLINT NOT NULL, 
    CONSTRAINT [PK_CustomerId] PRIMARY KEY CLUSTERED
    (
        [Id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)ON [PRIMARY]
GO
